listen: :443

tls:
  cert: /root/fullchain.cer
  key: /root/private.key

auth:
  type: password
  password: good

resolver:
  type: https
  https:
    addr: 1.1.1.1:443
    timeout: 10s

acl:
  inline: 
    - reject(all, udp/443)
