listen: :6443

tls:
  cert: /root/cert/cert.pem
  key: /root/cert/private.key

quic:
  initStreamReceiveWindow: 16777216
  maxStreamReceiveWindow: 16777216
  initConnReceiveWindow: 33554432
  maxConnReceiveWindow: 33554432
  
auth:
  type: password
  password: mwnv

resolver:
  type: https
  https:
    addr: 1.1.1.1:443
    timeout: 10s

masquerade: 
  type: proxy
  proxy:
    url: https://bing.com/ 
    rewriteHost: true
